"""added chaos_equality

Revision ID: c841cefa8837
Revises: 96c0e5c9f3fd
Create Date: 2026-06-18 21:36:17.737440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c841cefa8837'
down_revision: Union[str, Sequence[str], None] = '96c0e5c9f3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('chaos_equal', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('prev_chaos_equal', sa.Float(), nullable=True))
    op.drop_column('prices', 'prev_price')
    op.drop_column('prices', 'prev_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('prev_currency', sa.VARCHAR(length=50), nullable=True))
    op.add_column('prices', sa.Column('prev_price', sa.FLOAT(), nullable=True))
    op.drop_column('prices', 'prev_chaos_equal')
    op.drop_column('prices', 'chaos_equal')
    # ### end Alembic commands ###
